apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend
  namespace: trend
spec:
  replicas: 2
  selector: { matchLabels: { app: trend } }
  template:
    metadata: { labels: { app: trend } }
    spec:
      containers:
      - name: trend
        image: IMAGE_PLACEHOLDER
        ports: [{ containerPort: 3000 }]
        readinessProbe:
          httpGet: { path: "/", port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10
